version: 2
workflows:
  version: 2
  tests:
    jobs: &workflow_jobs
      - node6:
          filters:
            tags:
              only: /.*/
      - node8:
          filters:
            tags:
              only: /.*/
      - node10:
          filters:
            tags:
              only: /.*/
      - lint:
          requires:
            - node6
            - node8
            - node10
          filters:
            tags:
              only: /.*/
      - docs:
          requires:
            - node6
            - node8
            - node10
          filters:
            tags:
              only: /.*/
      - system_tests:
          requires:
            - lint
            - docs
          filters:
            branches:
              only: master
            tags:
              only: '/^v[\d.]+$/'
      - sample_tests:
          requires:
            - lint
            - docs
          filters:
            branches:
              only: master
            tags:
              only: '/^v[\d.]+$/'
      - publish_npm:
          requires:
            - system_tests
            - sample_tests
          filters:
            branches:
              ignore: /.*/
            tags:
              only: '/^v[\d.]+$/'
  nightly:
    triggers:
      - schedule:
          cron: 0 7 * * *
          filters:
            branches:
              only: master
    jobs: *workflow_jobs
jobs:
  node6:
    docker:
      - image: 'node:6'
    steps: &unit_tests_steps
      - checkout 
      - run: &npm_install_and_link
          name: Install and link the module.
          command: npm install
      - run: npm test
      - run: node_modules/.bin/codecov
  node8:
    docker:
      - image: 'node:8'
    steps: *unit_tests_steps
  node10:
    docker:
      - image: 'node:10'
    steps: *unit_tests_steps
  lint:
    docker:
      - image: 'node:10'
    steps:
      - checkout
      - run: *npm_install_and_link
      - run: &samples_npm_install_and_link
          name: Link the module being tested to the samples.
          command: |
            cd samples/
            npm install
            npm link ../
      - run:
          name: Run linting.
          command: npm run lint
  docs:
    docker:
      - image: 'node:10'
    steps:
      - checkout
      - run: *npm_install_and_link
      - run:
          name: Build documentation.
          command: npm run docs
  sample_tests:
    docker:
      - image: 'node:10'
    steps:
      - checkout
      - run:
          name: Decrypt credentials.
          command: |
            openssl aes-256-cbc -d -in .circleci/key.json.enc \
                -out .circleci/key.json \
                -k "${SYSTEM_TESTS_ENCRYPTION_KEY}"
      - run: *npm_install_and_link
      - run: *samples_npm_install_and_link
      - run:
          name: Run sample tests.
          command: npm run samples-test
          environment:
            GCLOUD_PROJECT: long-door-651
            GOOGLE_APPLICATION_CREDENTIALS: /var/dns/.circleci/key.json
      - run:
          name: Remove unencrypted key.
          command: rm .circleci/key.json
          when: always
    working_directory: /var/dns/
  system_tests:
    docker:
      - image: 'node:8'
    steps:
      - checkout
      - run:
          name: Decrypt credentials.
          command: |
            openssl aes-256-cbc -d -in .circleci/key.json.enc \
                -out .circleci/key.json \
                -k "${SYSTEM_TESTS_ENCRYPTION_KEY}"
      - run: *npm_install_and_link
      - run:
          name: Run system tests.
          command: npm run system-test
          environment:
            GOOGLE_APPLICATION_CREDENTIALS: .circleci/key.json
      - run:
          name: Remove unencrypted key.
          command: rm .circleci/key.json
          when: always
  publish_npm:
    docker:
      - image: 'node:10'
    steps:
      - checkout
      - run: 'echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc'
      - run: npm publish
